const cravings = [
  {
    temp_id: 1,
    name: "Chocolate",
    calories_min: 500,
    calories_max: 550,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 30,
    sugar_max: 35,
    fat_min: 25,
    fat_max: 30,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [1, 2],
  },
  {
    temp_id: 2,
    name: "Potato Chips",
    calories_min: 550,
    calories_max: 600,
    carbs_min: 55,
    carbs_max: 60,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 30,
    fat_max: 35,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [3, 4],
  },
  {
    temp_id: 3,
    name: "Ice Cream",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 25,
    sugar_max: 30,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [5, 6],
  },
  {
    temp_id: 4,
    name: "Pizza",
    calories_min: 600,
    calories_max: 650,
    carbs_min: 60,
    carbs_max: 65,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 25,
    fat_max: 30,
    protein_min: 15,
    protein_max: 20,
    additional_nutrition: {},
    alternatives: [7, 8],
  },
  {
    temp_id: 5,
    name: "Samosa",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [9, 10],
  },
  {
    temp_id: 6,
    name: "Burger",
    calories_min: 700,
    calories_max: 750,
    carbs_min: 70,
    carbs_max: 75,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 35,
    fat_max: 40,
    protein_min: 20,
    protein_max: 25,
    additional_nutrition: {},
    alternatives: [11, 12],
  },
  {
    temp_id: 7,
    name: "French Fries",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [13, 14],
  },
  {
    temp_id: 8,
    name: "Gulab Jamun",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 40,
    sugar_max: 45,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [15, 16],
  },
  {
    temp_id: 9,
    name: "Pani Puri",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [17, 18],
  },
  {
    temp_id: 10,
    name: "Cake",
    calories_min: 450,
    calories_max: 500,
    carbs_min: 45,
    carbs_max: 50,
    sugar_min: 35,
    sugar_max: 40,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [19, 20],
  },
  {
    temp_id: 11,
    name: "Cookies",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 25,
    sugar_max: 30,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [21, 22],
  },
  {
    temp_id: 12,
    name: "Noodles",
    calories_min: 500,
    calories_max: 550,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [23, 24],
  },
  {
    temp_id: 13,
    name: "Fried Chicken",
    calories_min: 600,
    calories_max: 650,
    carbs_min: 60,
    carbs_max: 65,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 35,
    fat_max: 40,
    protein_min: 20,
    protein_max: 25,
    additional_nutrition: {},
    alternatives: [25, 26],
  },
  {
    temp_id: 14,
    name: "Jalebi",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 45,
    sugar_max: 50,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [27, 28],
  },
  {
    temp_id: 15,
    name: "Doughnut",
    calories_min: 450,
    calories_max: 500,
    carbs_min: 45,
    carbs_max: 50,
    sugar_min: 30,
    sugar_max: 35,
    fat_min: 25,
    fat_max: 30,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [29, 30],
  },
  {
    temp_id: 16,
    name: "Pakora",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [31, 32],
  },
  {
    temp_id: 17,
    name: "Pasta",
    calories_min: 500,
    calories_max: 550,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [33, 34],
  },
  {
    temp_id: 18,
    name: "Butter Chicken",
    calories_min: 600,
    calories_max: 650,
    carbs_min: 60,
    carbs_max: 65,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 30,
    fat_max: 35,
    protein_min: 20,
    protein_max: 25,
    additional_nutrition: {},
    alternatives: [35, 36],
  },
  {
    temp_id: 19,
    name: "Brownie",
    calories_min: 450,
    calories_max: 500,
    carbs_min: 45,
    carbs_max: 50,
    sugar_min: 35,
    sugar_max: 40,
    fat_min: 25,
    fat_max: 30,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [37, 38],
  },
  {
    temp_id: 20,
    name: "Nachos",
    calories_min: 500,
    calories_max: 550,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 25,
    fat_max: 30,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [39, 40],
  },
  {
    temp_id: 21,
    name: "Kachori",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [41, 42],
  },
  {
    temp_id: 22,
    name: "Cheesecake",
    calories_min: 500,
    calories_max: 550,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 30,
    sugar_max: 35,
    fat_min: 30,
    fat_max: 35,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [43, 44],
  },
  {
    temp_id: 23,
    name: "Pav Bhaji",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 20,
    fat_max: 25,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [45, 46],
  },
  {
    temp_id: 24,
    name: "Milkshake",
    calories_min: 450,
    calories_max: 500,
    carbs_min: 45,
    carbs_max: 50,
    sugar_min: 40,
    sugar_max: 45,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [47, 48],
  },
  {
    temp_id: 25,
    name: "Chole Bhature",
    calories_min: 600,
    calories_max: 650,
    carbs_min: 60,
    carbs_max: 65,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 30,
    fat_max: 35,
    protein_min: 15,
    protein_max: 20,
    additional_nutrition: {},
    alternatives: [49, 50],
  },
  {
    temp_id: 26,
    name: "Candy",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 40,
    sugar_max: 45,
    fat_min: 5,
    fat_max: 10,
    protein_min: 1,
    protein_max: 3,
    additional_nutrition: {},
    alternatives: [51, 52],
  },
  {
    temp_id: 27,
    name: "Vada Pav",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [53, 54],
  },
  {
    temp_id: 28,
    name: "Tacos",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 20,
    fat_max: 25,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [55, 56],
  },
  {
    temp_id: 29,
    name: "Rasgulla",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 35,
    sugar_max: 40,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [57, 58],
  },
  {
    temp_id: 30,
    name: "Popcorn",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    alternatives: [59, 60],
  },
  {
    temp_id: 31,
    name: "Biryani",
    calories_min: 600,
    calories_max: 650,
    carbs_min: 60,
    carbs_max: 65,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 25,
    fat_max: 30,
    protein_min: 20,
    protein_max: 25,
    additional_nutrition: {},
    alternatives: [61, 62],
  },
  {
    temp_id: 32,
    name: "Pancakes",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [63, 64],
  },
  {
    temp_id: 33,
    name: "Momos",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [65, 66],
  },
  {
    temp_id: 34,
    name: "Muffins",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 25,
    sugar_max: 30,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [67, 68],
  },
  {
    temp_id: 35,
    name: "Hot Dog",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 25,
    fat_max: 30,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [69, 70],
  },
  {
    temp_id: 36,
    name: "Ladoo",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 30,
    sugar_max: 35,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [71, 72],
  },
  {
    temp_id: 37,
    name: "Sandwich",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [73, 74],
  },
  {
    temp_id: 38,
    name: "Dhokla",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [75, 76],
  },
  {
    temp_id: 39,
    name: "Waffles",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [77, 78],
  },
  {
    temp_id: 40,
    name: "Barfi",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 35,
    sugar_max: 40,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [79, 80],
  },
  {
    temp_id: 41,
    name: "Spring Rolls",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [81, 82],
  },
  {
    temp_id: 42,
    name: "Aloo Tikki",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [83, 84],
  },
  {
    temp_id: 43,
    name: "Cupcakes",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 25,
    sugar_max: 30,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [85, 86],
  },
  {
    temp_id: 44,
    name: "Cheese Fries",
    calories_min: 500,
    calories_max: 550,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 30,
    fat_max: 35,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [87, 88],
  },
  {
    temp_id: 45,
    name: "Mac And Cheese",
    calories_min: 500,
    calories_max: 550,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 25,
    fat_max: 30,
    protein_min: 15,
    protein_max: 20,
    additional_nutrition: {},
    alternatives: [89, 90],
  },
  {
    temp_id: 46,
    name: "Rasmalai",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 35,
    sugar_max: 40,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [91, 92],
  },
  {
    temp_id: 47,
    name: "Churros",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 30,
    sugar_max: 35,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [93, 94],
  },
  {
    temp_id: 48,
    name: "Fried Mozzarella Sticks",
    calories_min: 450,
    calories_max: 500,
    carbs_min: 45,
    carbs_max: 50,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 25,
    fat_max: 30,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    alternatives: [95, 96],
  },
  {
    temp_id: 49,
    name: "Tiramisu",
    calories_min: 450,
    calories_max: 500,
    carbs_min: 45,
    carbs_max: 50,
    sugar_min: 30,
    sugar_max: 35,
    fat_min: 25,
    fat_max: 30,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [97, 98],
  },
  {
    temp_id: 50,
    name: "Cinnamon Rolls",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 35,
    sugar_max: 40,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    alternatives: [99, 100],
  },
];

const alternatives = [
  {
    temp_id: 1,
    name: "Dark Chocolate",
    calories_min: 450,
    calories_max: 500,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar", "vegan"],
  },
  {
    temp_id: 2,
    name: "Cacao Nibs",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 25,
    fat_max: 30,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar", "vegan"],
  },
  {
    temp_id: 3,
    name: "Baked Sweet Potato Chips",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 4,
    name: "Air-Popped Popcorn",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 0,
    sugar_max: 5,
    fat_min: 5,
    fat_max: 10,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 5,
    name: "Frozen Yogurt",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 6,
    name: "Fruit Sorbet",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 0,
    fat_max: 5,
    protein_min: 1,
    protein_max: 3,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 7,
    name: "Whole Wheat Pizza",
    calories_min: 500,
    calories_max: 550,
    carbs_min: 50,
    carbs_max: 55,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 20,
    fat_max: 25,
    protein_min: 15,
    protein_max: 20,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 8,
    name: "Veggie Pizza",
    calories_min: 450,
    calories_max: 500,
    carbs_min: 45,
    carbs_max: 50,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["vegetarian"],
  },
  {
    temp_id: 9,
    name: "Baked Samosa",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 10,
    name: "Sweet Potato Samosa",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 11,
    name: "Veggie Burger",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 12,
    name: "Grilled Chicken Burger",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 20,
    protein_max: 25,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 13,
    name: "Baked Sweet Potato Fries",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 14,
    name: "Zucchini Fries",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["low-carb"],
  },
  {
    temp_id: 15,
    name: "Baked Gulab Jamun",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 16,
    name: "Date-Based Gulab Jamun",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 17,
    name: "Baked Pani Puri",
    calories_min: 150,
    calories_max: 200,
    carbs_min: 15,
    carbs_max: 20,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 18,
    name: "Sprouted Moong Pani Puri",
    calories_min: 100,
    calories_max: 150,
    carbs_min: 10,
    carbs_max: 15,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 0,
    fat_max: 5,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 19,
    name: "Whole Grain Cake",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 20,
    name: "Avocado Chocolate Mousse",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 21,
    name: "Oatmeal Cookies",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 22,
    name: "Almond Flour Cookies",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 23,
    name: "Zucchini Noodles",
    calories_min: 100,
    calories_max: 150,
    carbs_min: 10,
    carbs_max: 15,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["low-carb"],
  },
  {
    temp_id: 24,
    name: "Shirataki Noodles",
    calories_min: 50,
    calories_max: 100,
    carbs_min: 5,
    carbs_max: 10,
    sugar_min: 0,
    sugar_max: 5,
    fat_min: 0,
    fat_max: 5,
    protein_min: 1,
    protein_max: 3,
    additional_nutrition: {},
    dietary_tags: ["low-calorie"],
  },
  {
    temp_id: 25,
    name: "Grilled Chicken",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 20,
    protein_max: 25,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 26,
    name: "Baked Chicken Tenders",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 20,
    protein_max: 25,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 27,
    name: "Baked Jalebi",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 28,
    name: "Date-Based Jalebi",
    calories_min: 150,
    calories_max: 200,
    carbs_min: 15,
    carbs_max: 20,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 29,
    name: "Baked Doughnut",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 30,
    name: "Whole Grain Doughnut",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 31,
    name: "Baked Pakora",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 32,
    name: "Spinach Pakora",
    calories_min: 150,
    calories_max: 200,
    carbs_min: 15,
    carbs_max: 20,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-calorie"],
  },
  {
    temp_id: 33,
    name: "Whole Wheat Pasta",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 34,
    name: "Zucchini Pasta",
    calories_min: 100,
    calories_max: 150,
    carbs_min: 10,
    carbs_max: 15,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["low-carb"],
  },
  {
    temp_id: 35,
    name: "Tandoori Chicken",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 20,
    protein_max: 25,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 36,
    name: "Grilled Tofu",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 15,
    protein_max: 20,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 37,
    name: "Black Bean Brownie",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 38,
    name: "Avocado Brownie",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 39,
    name: "Baked Nachos",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 40,
    name: "Whole Grain Nachos",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 41,
    name: "Baked Kachori",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 42,
    name: "Moong Dal Kachori",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 43,
    name: "Greek Yogurt Cheesecake",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 20,
    fat_max: 25,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 44,
    name: "Coconut Milk Cheesecake",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 25,
    fat_max: 30,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 45,
    name: "Whole Wheat Pav",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 46,
    name: "Multigrain Pav",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-calorie"],
  },
  {
    temp_id: 47,
    name: "Almond Milk Shake",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 48,
    name: "Coconut Milk Shake",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 49,
    name: "Baked Bhature",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 50,
    name: "Whole Wheat Bhature",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 51,
    name: "Dark Chocolate-Covered Almonds",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 25,
    fat_max: 30,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["low-sugar", "high-protein"],
  },
  {
    temp_id: 52,
    name: "Homemade Granola Bars",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 53,
    name: "Baked Vada Pav",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 54,
    name: "Multigrain Vada Pav",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 55,
    name: "Whole Wheat Tacos",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 56,
    name: "Lettuce-Wrapped Tacos",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["low-carb"],
  },
  {
    temp_id: 57,
    name: "Sugar-Free Rasgulla",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 58,
    name: "Stevia-Sweetened Rasgulla",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 59,
    name: "Herbed Popcorn",
    calories_min: 150,
    calories_max: 200,
    carbs_min: 15,
    carbs_max: 20,
    sugar_min: 0,
    sugar_max: 5,
    fat_min: 5,
    fat_max: 10,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 60,
    name: "Spicy Popcorn",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 3,
    protein_max: 5,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 61,
    name: "Cauliflower Rice Biryani",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["low-carb"],
  },
  {
    temp_id: 62,
    name: "Quinoa Biryani",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 15,
    protein_max: 20,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 63,
    name: "Oat Flour Pancakes",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 64,
    name: "Banana Pancakes",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 65,
    name: "Steamed Momos",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 66,
    name: "Whole Wheat Momos",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 67,
    name: "Oatmeal Muffins",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 68,
    name: "Apple Cinnamon Muffins",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 69,
    name: "Turkey Hot Dog",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 15,
    protein_max: 20,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 70,
    name: "Veggie Hot Dog",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 71,
    name: "Date-Sweetened Ladoo",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 72,
    name: "Nut-Based Ladoo",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 73,
    name: "Grilled Veggie Sandwich",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 74,
    name: "Whole Grain Sandwich",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 75,
    name: "Steamed Dhokla",
    calories_min: 150,
    calories_max: 200,
    carbs_min: 15,
    carbs_max: 20,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 76,
    name: "Besan Dhokla",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 77,
    name: "Oat Flour Waffles",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 78,
    name: "Banana Waffles",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 5,
    fat_max: 10,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 79,
    name: "Date-Sweetened Barfi",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 80,
    name: "Nut-Based Barfi",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["high-protein"],
  },
  {
    temp_id: 81,
    name: "Baked Spring Rolls",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 82,
    name: "Tofu Spring Rolls",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 5,
    fat_max: 10,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 83,
    name: "Baked Aloo Tikki",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 84,
    name: "Sweet Potato Tikki",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 85,
    name: "Oat Flour Cupcakes",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 15,
    sugar_max: 20,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 86,
    name: "Avocado Cupcakes",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 87,
    name: "Baked Cheese Fries",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 20,
    fat_max: 25,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 88,
    name: "Sweet Potato Cheese Fries",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["gluten-free"],
  },
  {
    temp_id: 89,
    name: "Cauliflower Mac And Cheese",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["low-carb"],
  },
  {
    temp_id: 90,
    name: "Whole Wheat Mac And Cheese",
    calories_min: 400,
    calories_max: 450,
    carbs_min: 40,
    carbs_max: 45,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 20,
    fat_max: 25,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 91,
    name: "Sugar-Free Rasmalai",
    calories_min: 200,
    calories_max: 250,
    carbs_min: 20,
    carbs_max: 25,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 92,
    name: "Stevia-Sweetened Rasmalai",
    calories_min: 250,
    calories_max: 300,
    carbs_min: 25,
    carbs_max: 30,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 93,
    name: "Baked Churros",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 94,
    name: "Whole Wheat Churros",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 25,
    sugar_max: 30,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 95,
    name: "Baked Mozzarella Sticks",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 96,
    name: "Air-Fried Mozzarella Sticks",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 20,
    fat_max: 25,
    protein_min: 10,
    protein_max: 15,
    additional_nutrition: {},
    dietary_tags: ["low-fat"],
  },
  {
    temp_id: 97,
    name: "Sugar-Free Tiramisu",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 5,
    sugar_max: 10,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
  {
    temp_id: 98,
    name: "Avocado Tiramisu",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 10,
    sugar_max: 15,
    fat_min: 20,
    fat_max: 25,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["vegan"],
  },
  {
    temp_id: 99,
    name: "Whole Wheat Cinnamon Rolls",
    calories_min: 350,
    calories_max: 400,
    carbs_min: 35,
    carbs_max: 40,
    sugar_min: 25,
    sugar_max: 30,
    fat_min: 15,
    fat_max: 20,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["whole-grain"],
  },
  {
    temp_id: 100,
    name: "Date-Sweetened Cinnamon Rolls",
    calories_min: 300,
    calories_max: 350,
    carbs_min: 30,
    carbs_max: 35,
    sugar_min: 20,
    sugar_max: 25,
    fat_min: 10,
    fat_max: 15,
    protein_min: 5,
    protein_max: 7,
    additional_nutrition: {},
    dietary_tags: ["low-sugar"],
  },
];

export const seedData = {
  cravings,
  alternatives,
};
